In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('social_ads.csv')

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset = dataset.replace({'Male':1,'Female':-1})

/tmp/ipykernel_27377/3883185467.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset = dataset.replace({'Male':1,'Female':-1})


In [5]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575      -1   26            43000          0
3  15603246      -1   27            57000          0
4  15804002       1   19            76000          0

In [6]:
X =  dataset.drop('Purchased',axis=1)
y =  dataset['Purchased']

In [7]:
X = X.to_numpy()
y = y.to_numpy().reshape(-1,1)

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
X_train

array([[15603246,       -1,       27,    57000],
       [15704583,        1,       46,    28000],
       [15735549,       -1,       39,   134000],
       ...,
       [15680752,       -1,       43,   133000],
       [15579212,        1,       39,    77000],
       [15584545,       -1,       32,    86000]], shape=(320, 4))

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [12]:
X_train

array([[-1.19424348, -1.        , -1.06675246, -0.38634438],
       [ 0.21592346,  1.        ,  0.79753468, -1.22993871],
       [ 0.64683448, -1.        ,  0.11069205,  1.853544  ],
       ...,
       [-0.11569962, -1.        ,  0.50317355,  1.82445454],
       [-1.52869143,  1.        ,  0.11069205,  0.19544481],
       [-1.45447944, -1.        , -0.57615058,  0.45724994]],
      shape=(320, 4))

In [13]:
X_train =  np.hstack((np.ones((X_train.shape[0],1)),X_train))
X_test = np.hstack((np.ones((X_test.shape[0],1)),X_test))

In [14]:
X_train

array([[ 1.        , -1.19424348, -1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.21592346,  1.        ,  0.79753468, -1.22993871],
       [ 1.        ,  0.64683448, -1.        ,  0.11069205,  1.853544  ],
       ...,
       [ 1.        , -0.11569962, -1.        ,  0.50317355,  1.82445454],
       [ 1.        , -1.52869143,  1.        ,  0.11069205,  0.19544481],
       [ 1.        , -1.45447944, -1.        , -0.57615058,  0.45724994]],
      shape=(320, 5))

In [15]:
theta = np.zeros((X_train.shape[1],1))

In [16]:
theta

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [17]:
epochs = 1000
learning_rate = 0.01

In [18]:
for i in range(epochs):
    z = X_train @ theta
    y_pred = np.exp(z)/(1+np.exp(z))
    error = y_pred - y_train
    gradient = X_train.T@error/X_train.shape[0]
    theta = theta - learning_rate*gradient

In [19]:
y_pred

array([[0.09816244],
       [0.37449653],
       [0.69743784],
       [0.37543396],
       [0.66218629],
       [0.4254959 ],
       [0.35785774],
       [0.65847233],
       [0.16383845],
       [0.09828133],
       [0.72869091],
       [0.22531711],
       [0.35409198],
       [0.49478627],
       [0.04333591],
       [0.42665692],
       [0.95719678],
       [0.43918751],
       [0.93501585],
       [0.45057928],
       [0.9369697 ],
       [0.37695473],
       [0.39082999],
       [0.03669148],
       [0.21271234],
       [0.58215688],
       [0.41404169],
       [0.32119211],
       [0.76631687],
       [0.3204315 ],
       [0.12873965],
       [0.38290534],
       [0.6725295 ],
       [0.50703449],
       [0.69632275],
       [0.05571951],
       [0.0417226 ],
       [0.43900756],
       [0.40175906],
       [0.24621808],
       [0.17233456],
       [0.39745404],
       [0.32850885],
       [0.88669005],
       [0.35068623],
       [0.03639912],
       [0.34404941],
       [0.455

In [20]:
for i in range(y_pred.shape[0]):
    if y_pred[i]>0.505:
        y_pred[i]=1
    else:
        y_pred[i]=0
y_pred

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [21]:
y_train

array([[0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
    